
version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - api
      - ingest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_URL=http://api:8000
